### ISSUE TITLE
WordInsert can only use phonetic edit distance with python 2 wrapper. Fix it.

### ISSUE THREAD

**Issue by artificial-max** [eazteregg/Pun-Intended#13]
use rhymes

**Comment by eazteregg** [comment]
I tried implementing WordInsert such that it uses not rhymes, but phonetic edit distance. Unfortunately, this was not possible on the master branch, because some words in the idiom corpus cannot be found in the cmudict. Therefore, I built it on the graphem2phoneme branch which, albeit very slowly, circumvents that problem.

**Comment by artificial-max** [comment]
I'm getting the same error on my desktop pc as well as my laptop when trying to run main.py on the grapheme2phoneme branch:

Start search: "Sounds like x" "Has to do with y":
> lose alcohol
best result: booze
[('booze', 59), ("law's", 109), ('lows', 378), ('dues', 577), ("do's", 824)]
Puns: (•_•)  ( •_•)>⌐■-■  (⌐■_■)
Traceback (most recent call last):
  File "C:\Users\Max\Desktop\Pun_Generator\Pun-Intended\WordInsert.py", line 76, in insert_word
    phonrep2 = self.cmudict[word][0]
KeyError: 'ain'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 55, in <module>
    print(wi.insert_word())
  File "C:\Users\Max\Desktop\Pun_Generator\Pun-Intended\WordInsert.py", line 81, in insert_word
    phonrep2 = self.g2p.transcribeWord(word)
  File "C:\Users\Max\Desktop\Pun_Generator\Pun-Intended\g2pwrapper.py", line 42, in transcribeWord
    '%s' % fname], stdout=subprocess.PIPE)
  File "C:\Program Files\Anaconda3\lib\subprocess.py", line 693, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Program Files\Anaconda3\lib\subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "C:\Program Files\Anaconda3\lib\subprocess.py", line 1224, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] Das System kann die angegebene Datei nicht finden

**Comment by artificial-max** [comment]
Try python 2 to python 3 converter for g2p
